package com.geeks.mylocker.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.geeks.mylocker.dao.Folder;
import com.geeks.mylocker.dao.Record;
import com.geeks.mylocker.dao.Field;

import com.geeks.mylocker.dao.FolderDao;
import com.geeks.mylocker.dao.RecordDao;
import com.geeks.mylocker.dao.FieldDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig folderDaoConfig;
    private final DaoConfig recordDaoConfig;
    private final DaoConfig fieldDaoConfig;

    private final FolderDao folderDao;
    private final RecordDao recordDao;
    private final FieldDao fieldDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        folderDaoConfig = daoConfigMap.get(FolderDao.class).clone();
        folderDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        fieldDaoConfig = daoConfigMap.get(FieldDao.class).clone();
        fieldDaoConfig.initIdentityScope(type);

        folderDao = new FolderDao(folderDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);
        fieldDao = new FieldDao(fieldDaoConfig, this);

        registerDao(Folder.class, folderDao);
        registerDao(Record.class, recordDao);
        registerDao(Field.class, fieldDao);
    }
    
    public void clear() {
        folderDaoConfig.getIdentityScope().clear();
        recordDaoConfig.getIdentityScope().clear();
        fieldDaoConfig.getIdentityScope().clear();
    }

    public FolderDao getFolderDao() {
        return folderDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public FieldDao getFieldDao() {
        return fieldDao;
    }

}
